### PR TITLE
Update album.py to accept subfolders in config variable folder_format

### PR DESCRIPTION
**Pull request by cloud74pebble**
Correct handling of subfolders in config variable "folder_format"

e.g.:
[filepaths]
folder_format = "{albumartist}/{title} ({year})"

old method didn't allow creating subfolders by stripping "\" or "/"

### CODE REVIEW

**Comment by nathom** [comment]
I think this might cause unexpected behavior if there is a / in any metadata.

**Comment by cloud74pebble** [comment]
It doesn't affect any metadata.
It is just the storage-path in the filesystem.

with last release it was possible to sort the output to folders:
e.g. Albumartist/Albumtitle 
or Albumartist/Year/Albumtitle

Using the current dev-branch it wasn't possible anymore. 
This small patch fixed it.

**Comment by Delivator** [comment]
Bump

**Comment by nzoschke** [comment]
This works for me too

**Comment by nzoschke** [comment]
> I think this might cause unexpected behavior if there is a / in any metadata.

This looks to be handled properly. 

Metadata `albumartist`, `albumcomposer`, `title` all pass through `clean_filename` before being passed as the format kwargs. So if that metadata has `/` it is stripped then used as subpaths for the `folder_format` when it contains `/`.

**Pull request merged**
