### PR TITLE
[Deezer] fix download on special files

### PR DESCRIPTION
**Pull request by AurelReb**
- Personal medias can now be downloaded without error.
- Tracks failing because bad permissions are now retried with fallback song.
- streamrip/exceptions.py has been converted from CRLF to LF format to standardize with other files.

### CODE REVIEW

**Comment by AurelReb** [comment]
It seems the main developer is working on the `rewrite` branch, so I don't know if the main branch is still maintained

**Comment by nathom** [comment]
@AurelReb Can you provide a link where this fixes the issue?

**Comment by AurelReb** [comment]
> @AurelReb Can you provide a link where this fixes the issue?

@nathom  As stated in #487 you can test it with the following command:
`rip url https://www.deezer.com/fr/playlist/9122405722`

**Comment by AurelReb** [comment]
for personal mp3 uploaded musics, you can only test it with a playlist that includes one of your mp3 because mp3s are purely personal on deezer.

**Comment by nathom** [comment]
Fix for v2 merged into dev.

**Pull request closed without merging**
